name: CI

on:
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/ci.yml

jobs:
  build_and_install_liburing:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: liburing
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: ./configure
      - run: make
      - run: make install

  test:
    runs-on: ubuntu-latest
    needs: build_and_install_liburing
    steps:
      - uses: actions/checkout@v2
      - run: python configure.py
      - run: make
