name: CI

on:
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/ci.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/cache@v3
        env:
          cache-name: cache-liburing
        with:
          path: ./liburing
          key: ${{ hashFiles('liburing') }}
      - run: |
          cd liburing
          ./configure
          make
          sudo make install
      - run: python configure.py
      - run: make
      - run: echo "test cache"
