name: CI

on:
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/ci.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: |
          cd liburing
          ./configure
          make
          sudo make install
      - run: python configure.py
      - run: make
